### ISSUE TITLE
plugin list in json format

### ISSUE THREAD

**Issue by AdriaanBoshoff** [theumod/uMod.Rust#125]
Rust gives us `playerlist` that returns all players in json format for rcon clients. Adding `o.pluginlist` that returns plugins in json would be amazing for rcon clients. I'll buy you a pizza.

**Comment by austinv900** [comment]
The current Oxide/uMod configuration isn't optimized to handle custom responses to the rcon protocol

**Comment by AdriaanBoshoff** [comment]
I don't fully understand what you mean by custom responses. Wouldn't it just be a normal command? Other commands like `o.plugins` already sends to the rcon too.

**Comment by austinv900** [comment]
`o.plugins` shows on rcon because it gets sent along with the standard logging method. But anything oxide outputs gets outputted to the logfiles and the local server console instead of just rcon. It would be possible to set it up in the manor your talking about but would cause bloating of the logfile and standard output of the local server console.

**Comment by austinv900** [comment]
I wouldn't be to hard to implement but it would require a game specific command baked in. But idk how well that would go over with wulf as not all the supported games support rcon

**Comment by AdriaanBoshoff** [comment]
I understand the log file issue. However it wont get outputted to the standard console if a rcon client runs it. The Rust rcon doesn't seem to output things to the main console. For example if you run send `o.plugins` from a rcon with lets say a Identifier with a value of 5. It only reports back to the rcon that sent that command. It also sends back the identifier value so its easy to keep track of responses.

**Comment by austinv900** [comment]
Interesting as oxide doesn't respect identifiers and just uses the log methods

**Comment by AdriaanBoshoff** [comment]
I think it will still output to the logfile but not the main console window

**Comment by AdriaanBoshoff** [comment]
nvm. I do apologize for my ignorance. It seems it does output to the main window. I might have been thinking about something else

**Comment by AdriaanBoshoff** [comment]
However I still believe this should be a thing

**Comment by austinv900** [comment]
All good man. Your quantum right?

**Comment by AdriaanBoshoff** [comment]
I am

**Comment by lukespragg** [comment]
This won't be possible until the universal commands have some sort of integration with RCON to uniquely identify where to send the JSON response, else the local server console and log file would end up getting spammed with useless info.
