### ISSUE TITLE
HTNPlayer target hook doesn't work

### ISSUE THREAD

**Issue by EgorBlagov** [theumod/uMod.Rust#127]
Hi,

Thanks a lot for this project. I found these lines in your code:
https://github.com/theumod/uMod.Rust/blob/develop/src/RustHooks.cs#L579

But I can't get it to work, my HTNPlayers still attack me even if I return false.

I tried to use these varations:
```
// Hide from HTN player
        private object OnNpcPlayerTarget(BaseEntity npc, BaseEntity entity) {
            if (npc is HTNPlayer) {
                    return false;
            }

            return null;
        }

// or 
        private object OnNpcPlayerTarget(HTNPlayer npc, BaseEntity entity) {
            return false;
        }

```

I'm wondering if it is integrated, or when will it be integrated. I think it's pretty critical since facepunch implemented cargoships with htn based scientists, millitary tunnel with htn based scientists as well as last update's htn based scientists around the roads. Oh and haloween scarecrows (which use MurdererDomain and MurdererDefinition and also are HTN's).

Please help me if I do something wrong.

Thanks & regards,
Egor.

**Comment by lukespragg** [comment]
The hooks for HTNPlayer are not enabled because of issues with the hook calling.
