### ISSUE TITLE
Error using Linux : ArgumentOutOfRangeException: Value must be positive and below the buffer height.

### ISSUE THREAD

**Issue by chenshuhao** [theumod/uMod.Rust#135]
Error using Linux : ArgumentOutOfRangeException: Value must be positive and below the buffer height.

thinks!

**Comment by lukespragg** [comment]
Please use our forums at https://umod.org/community/rust/5699-argumentoutofrangeexception-value-must-be-positive-and-below-the-buffer-height-parameter-name-top for general issues.

**Comment by chenshuhao** [comment]
This post is from me. Today, I accidentally replaced Assembly-CSharp.dll on the Windows server side with Linux, and the same error occurred. But previous versions were generic.
