### ISSUE TITLE
Quality of life request: Default branch master not develop in Repo settings.

### ISSUE THREAD

**Issue by Codingale** [theumod/uMod.Rust#139]
Can you make it master, or Oxide if that's where "polished" code is? IE a good fork location if someone wants to check on updates or contribute.

 ![Branch Options](https://user-images.githubusercontent.com/6324853/52530916-79891e00-2cdb-11e9-9061-7f9f1e2cd6a8.png)

**Comment by Calytic** [comment]
Why? "master" is the current "release" branch, but not the branch we work from
1) We don't accept requests made directly to master, they must be tested first
2) "master" represents our official upstream, and is currently sourced from the "oxide" branch.  However, it feature frozen and only receiving critical fixes
3) "develop" is where the most "polished", or latest, uMod development is taking place.  And once ready, will replace the "oxide" branch

**Comment by Codingale** [comment]
Ah, perhaps I'm confused about the flow you do these things. Just each time I come to check on progress or view something it's on develop which wasn't update lately but releases are still being made from master.

I completely understand not accepting PRs for the master branch (only develop). 
Develop to me seems not not be having updates recently (likely due to new update I understand) but it, and oxide is getting merged into the frozen master branch.

Yeah I could git clone and pull the changes and get a brief change log there as I'm just glancing, only a suggestion.From an outsider looking in to see the latest thing being changed at the moment (typically master / oxide) but if it's just due to the patch I understand; just was confused.

**Comment by Calytic** [comment]
Regarding the develop branch, we're mostly done implementing the migration from oxide to uMod.  Much of the functionality that used to exist in uMod.Rust has been universalized and moved uMod.Core, we're in a testing and cleanup phase to ensure that both (uMod.Rust & uMod.Core develop) will work across the many thousands of servers that use the technology.  The develop branch is a significant departure from the oxide branch, so we have to make sure it's fully working before deployment.
