### ISSUE TITLE
NullReferenceException's after update to 2.0.4178

### ISSUE THREAD

**Issue by Memphizzz** [theumod/uMod.Rust#143]
Hi,

i've just updated from 2.0.4174 to 2.0.4178. After this update the server keeps spamming these NullReferenceException's:

NullReferenceException: Object reference not set to an instance of an object
  at HackableLockedCrate.DisableRB () [0x00009] in <6497642b7b9f41fb91a4208bcdeb8c16>:0
  at HackableLockedCrate.LandCheck () [0x00051] in <6497642b7b9f41fb91a4208bcdeb8c16>:0
  at InvokeHandler.DoTick () [0x000d6] in <c2be72503c5a40febe59f0b53169db91>:0
  at InvokeHandler.LateUpdate () [0x0000c] in <c2be72503c5a40febe59f0b53169db91>:0

(Filename: <6497642b7b9f41fb91a4208bcdeb8c16> Line: 0)

Going back to 4174 fixes the problem. Please check.
P.S.: I've disabled all plugins while testing this.

Thanks for Oxide and keep up the great work!

**Comment by lukespragg** [comment]
That is not an error from Oxide. The only change in our update was patching for the new Rust version and changes. Installing an old Oxide build downgrades your Rust version, hence the difference.

**Comment by Memphizzz** [comment]
@lukespragg I see, can you point me in the right direction for this bug? Do you see it too? With this downgraded version im still able to connect fine with the latest client, is that a problem? Or does all this come down to waiting for an update from facepunch?

**Comment by Calytic** [comment]
We never recommend downgrading, it is not supported by our upstream currently and you will have mixed results.  As lukespragg said, this error is not related to Oxide and there isn't anything we can do to fix it.
